/*
    Author: Steven Hermans
*/
$("body").ready(function(){installPaperInteractListener();});function installPaperInteractListener(){$(".paper-interact").unbind("mousedown");$(".paper-interact").unbind("mouseup");$(".paper-interact").unbind("mousemove");$(".paper-interact").unbind("touchstart");$(".paper-interact").unbind("touchend");$(".paper-interact").unbind("touchmove");$(".paper-interact").unbind("click");$("a.paper-interact").each(function(){if($(this).attr("href")!==""||typeof($(this).attr("href"))!=="undefined"){$(this).attr("data-href",$(this).attr("href"));$(this).removeAttr("href");}});$(".paper-interact").mousedown(function(event){paperInteractMouseDown(this,event);});$(".paper-interact").bind("touchstart",function(event){paperInteractMouseDown(this,event);return true;});$(".paper-interact").mouseup(function(){paperInteractMouseUp(this);});$(".paper-interact").bind("touchend",function(){paperInteractMouseUp(this);});$(".paper-interact").mousemove(function(){paperInteractMouseMove(this);});$(".paper-interact").bind("touchmove",function(){paperInteractMouseMove(this);});$(".paper-interact").click(function(){return paperInteractClick(this);});installMobilePaperInteractListener();$(window).resize(function(){installMobilePaperInteractListener();});}
function installMobilePaperInteractListener(){$("a.paper-interact.mobile").each(function(){$(this).attr("href",$(this).attr("data-href"));$(this).removeAttr("data-href");});$(".paper-interact.mobile").unbind("mousedown");$(".paper-interact.mobile").unbind("mouseup");$(".paper-interact.mobile").unbind("mousemove");$(".paper-interact.mobile").unbind("touchstart");$(".paper-interact.mobile").unbind("touchend");$(".paper-interact.mobile").unbind("touchmove");$(".paper-interact.mobile").unbind("click");if($(window).width()<600){$("a.paper-interact.mobile").each(function(){if($(this).attr("href")!==""||typeof($(this).attr("href"))!=="undefined"){$(this).attr("data-href",$(this).attr("href"));$(this).removeAttr("href");}});$(".paper-interact.mobile").mousedown(function(event){paperInteractMouseDown(this,event);});$(".paper-interact.mobile").bind("touchstart",function(event){paperInteractMouseDown(this,event);return true;});$(".paper-interact.mobile").mouseup(function(){paperInteractMouseUp(this);});$(".paper-interact.mobile").bind("touchend",function(){paperInteractMouseUp(this);});$(".paper-interact.mobile").mousemove(function(){paperInteractMouseMove(this);});$(".paper-interact.mobile").bind("touchmove",function(){paperInteractMouseMove(this);});$(".paper-interact.mobile").click(function(){return paperInteractClick(this);});}}
function paperInteractMouseDown(tthis,event){w=$(tthis).width();w+=parseInt($(tthis).css("padding-left"));w+=parseInt($(tthis).css("padding-right"));h=$(tthis).height();h+=parseInt($(tthis).css("padding-top"));h+=parseInt($(tthis).css("padding-bottom"));size=Math.sqrt(Math.pow(w,2)+Math.pow(h,2))*2;var offset=$(tthis).offset();x=Math.round(event.pageX-offset.left)-size/2;y=Math.round(event.pageY-offset.top)-size/2;color=findBackgroundColor(tthis);cls="overlay"+(color.isLight()?" dark":"");html="<div class='"+cls+"' style='width: "+size+"px; height: "+size+"px; top: "+y+"px; left: "+x+"px'/>";$(tthis).append(html);setTimeout(function(){var tick=0;var overlay=$(tthis).children(".overlay").last();var interval=window.setInterval(function(){tick++;var scale=tick/100;overlay.css("transform","scale("+scale+","+scale+")");if(overlay.hasClass("expand")){overlay.css("transform","");window.clearInterval(interval);}
if(tick==100){window.clearInterval(interval);}},20);},10);}
function paperInteractMouseUp(tthis){var overlay=$(tthis).children(".overlay");overlay.addClass("ani");setTimeout(function(){overlay.addClass("expand");setTimeout(function(){overlay.addClass("hide");setTimeout(function(){overlay.remove();},300);},200);},10);}
function paperInteractMouseMove(tthis){$(tthis).mouseup();}
function paperInteractClick(tthis){if($(tthis).hasClass("trickered")){return true;}
setTimeout(function(){href=$(tthis).attr("data-href");if(typeof(href)!=="undefined"){window.location.href=href;}else{$(tthis).addClass("trickered");$(tthis).click();}},300);return false;}
function findBackgroundColor(comp){try{bg=$(comp).css("background-color");if(bg==="transparent"){return findBackgroundColor($(comp).parent());}else if(bg.indexOf("rgba")==0){bg=bg.substring(5,bg.length-1);clrs=bg.split(",");if(parseInt(clrs[3])==0){return findBackgroundColor($(comp).parent());}else{return new PaperColor(parseInt(clrs[0]),parseInt(clrs[1]),parseInt(clrs[2]));}}else{bg=bg.substring(4,bg.length-1);clrs=bg.split(",");return new PaperColor(parseInt(clrs[0]),parseInt(clrs[1]),parseInt(clrs[2]));}}catch(e){console.error(e);return new PaperColor(255,255,255);}}
function PaperColor(r,g,b){this.r=r;this.g=g;this.b=b;}
PaperColor.prototype.isLight=function(){return(this.r+this.g+this.b)/3>120;};var DEFAULT_LIST_HTML=null;var DEFAULT_LIST_ITEM=null;$("body").ready(function(){installPaperHeaderListener();installDrawerListener();});function installPaperHeaderListener(){$(".paper-header .paper-header-menu-right-toggle").unbind("click");$(".paper-header .paper-header-menu-right-toggle").click(function(){cmp=$(this).next(".paper-header-menu-right");if($(this).hasClass("active")){$(this).removeClass("active");cmp.addClass("tmp");cmp.removeClass("active");setTimeout(function(){cmp.removeClass("tmp");},200);}else{$(this).addClass("active");cmp.addClass("tmp");setTimeout(function(){cmp.addClass("active");cmp.removeClass("tmp");},10);}});$(".paper-header .paper-header-menu-button").unbind("click");$(".paper-header .paper-header-menu-button").click(function(){menu=$(".paper-header .paper-header-menu");if(menu.hasClass("active")){menu.removeClass("active");$(".paper-header .paper-header-menu-back").removeClass("active");setTimeout(function(){$(".paper-header .paper-header-menu-back").remove();},200);}else{menu.addClass("active");menu.before("<div class='paper-header-menu-back'/>");setTimeout(function(){$(".paper-header .paper-header-menu-back").addClass("active");$(".paper-header .paper-header-menu-back").click(function(){$(".paper-header .paper-header-menu-button").click();});},10);}});$(window).resize(function(){fixHeaderHeight();});$(window).scroll(function(){fixHeaderHeight();});$(".paper-content, .paper-content.drawer .drawer-content").scroll(function(){fixHeaderHeight();});fixHeaderHeight();}
function fixHeaderHeight(){h=$(window).height();w=$(window).width();if((h<600&&w>600)||(h<480&&w<=600)){$(".paper-header.auto").removeClass("large");$(".paper-content").removeClass("large");$(".paper-header.auto").css("height","");$(".paper-header.auto .paper-header-content").css("margin-top","");$(".paper-header.auto .paper-header-menu-button").css("top","");$(".paper-content").css("top","");icon=$(".paper-header.auto .icon");icon.css("opacity","");icon.css("width","");icon.css("height","");icon.css("margin-right","");icon.css("margin-left","");}else{$(".paper-header.auto").addClass("large");$(".paper-content").addClass("large");scrollTop=$(window).scrollTop()+$(".paper-content").scrollTop()+$(".paper-content.drawer .drawer-content").scrollTop();if(scrollTop==0){$(".paper-header.auto").css("height","");$(".paper-header.auto .paper-header-content").css("margin-top","");$(".paper-header.auto .paper-header-menu-button").css("top","");$(".paper-content").css("top","");icon=$(".paper-header.auto .icon");icon.css("opacity","");icon.css("width","");icon.css("height","");icon.css("margin-right","");icon.css("margin-left","");}else{cTop=$(".paper-content").scrollTop()+$(".paper-content.drawer .drawer-content").scrollTop();if(cTop>54){cTop=54;}
cTop=144-cTop;$(".paper-content").css("top",cTop+"px");sTop=scrollTop;if(sTop>54){sTop=54;}
nh=144-sTop;nh2=54-sTop;$(".paper-header.auto").css("height",nh+"px");$(".paper-header.auto .paper-header-content").css("margin-top",nh2+"px");if(w<600){$(".paper-header.auto .paper-header-menu-button").css("top","30px");icon=$(".paper-header.auto .icon");icon.css("opacity","0");icon.css("width","0px");icon.css("height","0px");icon.css("margin-right","0px");icon.css("margin-left","30px");}}}
if($(".paper-header.auto").hasClass("large")){}else{$(".paper-header.auto").css("height","");}}
function installDrawerListener(){if(DEFAULT_LIST_HTML==null){DEFAULT_LIST_ITEM=$(".paper-content .drawer-nav .paper-list-header.active");DEFAULT_LIST_HTML=$(".paper-content .drawer-content").html();}
$(".paper-content .drawer-nav .paper-list-header").unbind("click");$(".paper-content .drawer-nav .paper-list-header").click(function(){if(typeof($(this).attr("data-link"))!=="undefined"){if(!$(this).hasClass("active")){$(".drawer-nav li.paper-list-header").removeClass("active");$(this).addClass("active");$(".paper-content .drawer-content").addClass("hidden");$(".paper-content .drawer-content").addClass("active");$(".paper-content .drawer-nav").addClass("active");if($(window).width()<600){$(".paper-content .drawer-content-o").html("");}
var startTime=new Date().getTime();var title=$(this).children(".paper-list-title").html().trim();var key=$(this).attr("data-key");var url=document.URL;if(url.indexOf("#")!=-1){url=url.split("#")[0];}
var url=url+"#"+key;getter=$.get($(this).attr("data-link"));getter.done(function(data){history.pushState(data,title,url);var difTime=300-(new Date().getTime()-startTime);if(difTime<0){difTime=0;}
setTimeout(function(){$(".paper-content .drawer-content-o").html(data);setTimeout(function(){$(".paper-content .drawer-content").removeClass("hidden");},10);},difTime);});getter.fail(function(xhr){if(xhr.status==500){history.pushState("e:Something went wrong",title,url);error("Something went wrong");}else{history.pushState("e:Connection error",title,url);error("Connection error");}});}}});window.onpopstate=function(event){$(".drawer-nav li.paper-list-header").removeClass("active");if(document.URL.indexOf("#")!=-1){var key=document.URL.split("#")[1];$(".drawer-nav li.paper-list-header[data-key='"+key+"']").addClass("active");}else{DEFAULT_LIST_ITEM.addClass("active");}
var timeout=$(".paper-content .drawer-content").hasClass("hidden")?0:300;if(timeout==300){$(".paper-content .drawer-content").addClass("hidden");}
$(".paper-content .drawer-content").removeClass("active");$(".paper-content .drawer-nav").removeClass("active");setTimeout(function(){if(document.URL.indexOf("#")!=-1){$(".paper-content .drawer-content").addClass("active");$(".paper-content .drawer-nav").addClass("active");$(".paper-content .drawer-content-o").html(event.state);setTimeout(function(){$(".paper-content .drawer-content").removeClass("hidden");},10);}else{$(".paper-content .drawer-content-o").html(DEFAULT_LIST_HTML);setTimeout(function(){$(".paper-content .drawer-content").removeClass("hidden");},10);}},timeout);};if(document.URL.indexOf("#")!=-1){var key=document.URL.split("#")[1];$(".drawer-nav .drawer-nav .paper-list-header[data-key='"+key+"']").click();}}
function updateDrawerLayout(){}$("body").ready(function(){installPaperListListener();});function installPaperListListener(){$(".paper-list div, .paper-list i").unbind("click");domQuery=".paper-list .paper-list-item.expandable > .paper-list-header, .paper-list .paper-list-item.toggle > .paper-list-header";headers=$(domQuery).click(function(){header=$(this);parent=$(this).parent();ul=parent.children("ul");if(ul.hasClass("hidden")){ul.removeClass("hidden");}else{if(!parent.hasClass("toggle")){ul.addClass("hidden");}else if(header.hasClass("active")){ul.addClass("hidden");}}
if($(this).parent().hasClass("toggle")){$(".paper-list .paper-list-header.active").removeClass("active");$(this).addClass("active");}});headers.children(".paper-list-control").click(function(){return false;});headers.children(".paper-list-wrap1, .paper-list-wrap2, .paper-list-wrap3, .paper-list-wrap4").children(".paper-list-control").click(function(){return false;});}$("body").ready(function(){installPaperInputListener();});function installPaperInputListener(){$(".paper-input input, .paper-input textarea").unbind("keyup");$(".paper-input input, .paper-input textarea").unbind("focus");$(".paper-input input, .paper-input textarea").unbind("blur");$(".paper-input input, .paper-input textarea").keyup(function(){$passed=validatePaperInput(this);$stat=$(this).parent().children(".stat_active");$label=$(this).parent().children("label");if($passed){$stat.css("background-color","#2196F3");$label.css("color","#2196F3");}else{$stat.css("background-color","#E87C71");$label.css("color","#E87C71");}});$(".paper-input label").click(function(){$(this).next().focus();});$(".paper-input input, .paper-input textarea").focus(function(){$passed=validatePaperInput(this);$stat=$(this).parent().children(".stat_active");$label=$(this).parent().children("label");$label.addClass("selected");if($passed){$stat.css("background-color","#2196F3");$label.css("color","#2196F3");}else{$stat.css("background-color","#F44336");$label.css("color","#F44336");}
$stat.css("width",$stat.parent().width()-20+"px");});$(".paper-input input, .paper-input textarea").blur(function(){$(this).parent().children("label").css("color","");if($(this).val()==null||$(this).val()==""){$(this).parent().children("label").removeClass("selected");}
$(this).parent().children(".stat_active").css("width","");});$(".paper-input.label input, .paper-input.label textarea").each(function(){if($(this).val()==null||$(this).val()==""){$(this).parent().children("label").removeClass("selected");}else{$(this).parent().children("label").addClass("selected");}});};var validatePaperInput=function($input){$value=$($input).val();required=$($input).attr("required");$max_length=$($input).attr("max-length");$email=$($input)[0].type=="email";$youtube=false;$cls=$($input).attr("class");if($cls!=null){$youtube=$cls.indexOf("ytb-field")>-1;}
$passed=true;if(required&&($value==null||$value=="")&&false){$passed=false;}
if($max_length&&$value!=null){if($value.length>$max_length){$passed=false;}}
if($email&&$value!=null){var atpos=$value.indexOf("@");if(atpos<1||atpos+1>=$value.length){$passed=false;}}
if($youtube){if(!isValidYoutubeCode($value)){$passed=false;}}
return $passed;};function setPaperButtonState(button,loading){if(loading){button.next().css("opacity",0);if(button.children(".paper-loading").length==0){button.children("span").css("opacity",0);button.append('<svg class="paper-loading small white center" style="opacity:0" viewBox="0 0 52 52"><circle class="path" cx="26px" cy="26px" r="20px" fill="none" stroke-width="4px" /></svg>');setTimeout(function(){button.children().last().css("opacity",1);},200);}}else{button.children().last().css("opacity",0);setTimeout(function(){button.children("span").css("opacity",1);button.children().last().remove();},200);}}
function setPaperButtonError(button,error){button.next().html(error);button.next().css("opacity",1);}
function hidePaperButtonError(button){button.next().html("");button.next().css("opacity",0);}$THEME_INFO='modal-info';$THEME_WARNING='modal-warning';$THEME_ERROR='modal-error';$THEME_QUESTION='modal-question';$THEME_INPUT='modal-input';function infoPaperPop($action,$title,$message,$btn_ok){paperPop($action,$THEME_INFO,$title,$message,false,$btn_ok);}
function warningPaperPop($action,$title,$message,$btn_cancel,$btn_ok){paperPop($action,$THEME_WARNING,$title,$message,$btn_cancel,$btn_ok);}
function errorPaperPop($action,$title,$message,$btn_cancel,$btn_ok){paperPop($action,$THEME_ERROR,$title,$message,$btn_cancel,$btn_ok);}
function questionPaperPop($action,$title,$message,$btn_cancel,$btn_ok){paperPop($action,$THEME_QUESTION,$title,$message,$btn_cancel,$btn_ok);}
function inputPaperPop($action,$title,$value,$btn_cancel,$btn_ok,$placeholder,$required){if($value==null){$value="";}
if($placeholder==null){$placeholder="";}
$message="<form onsubmit='$(\".paper-modal .paper-modal-footer .actionbtn\").click(); return false;'>\n\
            <div class='paper-input label'>\n\
            <div class='paper-input-field'>\n\
            <label>"+$placeholder+"</label>\n\
            <input type='text' value='"+$value+"' name='modal-input'";if($required){$message+=" required=''";}
$message+=">\n\
            <div class='stat'></div>\n\
            <div class='stat_active'></div></div></form>";if($btn_cancel==null){$btn_cancel="Annuleren";}
if($btn_ok==null){$btn_ok="Opslaan";}
paperPop($action,$THEME_INPUT,$title,$message,$btn_cancel,$btn_ok);}
function paperPop($action,$theme,$title,$message,$btn_cancel,$btn_ok){$(".paper-modal").remove();$("body").append(generatePaperModalHTML($theme,$title,$message,$btn_cancel,$btn_ok));setTimeout(function(){installListeners();show();},10);var FADE_TIME=500;this.action=$action;var installListeners=function(){$(".paper-modal").click(function(){destroy();}).children().click(function(){return false;});$(".paper-modal .paper-modal-footer .btn-default").click(function(){destroy();});$(".paper-modal .paper-modal-footer .actionbtn").click(function(){if($theme===$THEME_INPUT&&$("input[name='modal-input']").prop('required')){if($("input[name='modal-input']").val()==null||$("input[name='modal-input']").val()===""){$("input[name='modal-input']").focus();$stat=$("input[name='modal-input']").parent().children(".mat_input_stat_active");$label=$("input[name='modal-input']").parent().children("label");$stat.css("background-color","#F44336");$label.css("color","#F44336");return;}}
destroy();if($action&&(typeof $action=="function")){if($theme===$THEME_INPUT){$action($("input[name='modal-input']").val());}else{$action();}}});if($theme===$THEME_INPUT){initMaterialForms();$("input[name='modal-input']").select();}};var show=function(){$(".paper-modal").css("opacity",1);$(".paper-modal").css("left","0px");$(".paper-modal").css("right","0px");}
var destroy=function(){$(".paper-modal").css("opacity","");$(".paper-modal").css("left","");$(".paper-modal").css("right","");setTimeout(function(){$(".paper-modal").remove();},FADE_TIME);};}
function generatePaperModalHTML($theme,$title,$message,$btn_cancel,$btn_ok){if($theme==null){$theme=$THEME_INFO;}
if($title==null){$title="Modal title";}
if($message==null){$message="One fine body...";}
if($btn_cancel==null){$btn_cancel="Annuleren";}
if($btn_ok==null){$btn_ok="Oke";}
if($theme==$THEME_INFO){buttonType="";}else if($theme==$THEME_WARNING){buttonType=" orange";}else if($theme==$THEME_ERROR){buttonType=" red";}else if($theme==$THEME_QUESTION){buttonType="";}else if($theme==$THEME_INPUT){buttonType="";}else{throw"Unknown theme: "+$theme;}
btn_cancel_html=($btn_cancel===false?"":"<button type='button' class='btn btn-default' data-dismiss='modal'>"+$btn_cancel+"</button>");return"<div class='paper-modal "+$theme+"'>\n\
        <div class='paper-modal-dialog'>\n\
            <div class='paper-modal-content'>\n\
                <div class='paper-modal-header'>\n\
                    <h4 class='paper-modal-title'>"+$title+"</h4>\n\
                </div>\n\
                <div class='paper-modal-body'>\n\
                    "+$message+"\n\
                </div>\n\
                <div class='paper-modal-footer"+buttonType+"'>\n\
                    "+btn_cancel_html+"\n\
                    <button type='button' class='btn actionbtn'>"+$btn_ok+"</button>\n\
                </div>\n\
            </div>\n\
        </div>\n\
    </div>";}$("body").ready(function(){installPaperPopupListener();});function installPaperPopupListener(){$(".paper-popup-action").unbind("click");$(".paper-popup-action").click(function(){var parent=$(this);var popup=parent.children(".paper-popup.hidden");if(popup.length!=0){showMDPopup(popup,true);}});}
function showMDPopup(popup,first){popup.parent().before("<div class='paper-popup-overview'/>");popup.addClass("tmp");popup.removeClass("hidden");setTimeout(function(){h=popup.children("ul").height()+20;popup.css("height",h+"px");popup.removeClass("tmp");if(first){var overview=$(".paper-popup-overview");overview.unbind("click");overview.click(function(){hideMDPopup($(".paper-popup"));});}},10);}
function hideMDPopup(popup){$(".paper-popup-overview").remove();popup.addClass("tmp");setTimeout(function(){popup.addClass("hidden");popup.removeClass("tmp");},200);}